window["runtimeConfig"] = {
  hubbleConfig: {
    "mainnet-beta": {
      borrowing: {
        programId: "6JbR96VWfG5P2eFCBPRDFenw6poqGP7RoA4vqx5tNBJf",
        accounts: {
          stablecoinMint: "6w7WUkBpfZwejqesCMgXUTdbtZdGThu1882BNiLzTwc8",
          stablecoinMintAuthority: "2okhqAYAsxcDLWxaKdAJ38G2By9HwDdhTmTmY84UftHP",
          mint: {
            ETH: "htC6eTvy3pUSi2wCurvczo5ZyX9vBBzvPMU4PFxr3TP",
            BTC: "HAKEyaEmSUjMFU4qwXd6mf2Sj5Zas5667w6rcuPBuPst",
            SRM: "GosaYdcVQSAvBjYhfgbHfT1k9LcHZBK9uGUV67J8BDT8",
            RAY: "FG2vjWXXBDYgqj5rZ5VnmTL784KmQaDBRivKJGz3cpTs",
            FTT: "AHgeW347LLVBSU7upSUCnffgSH1ZpuQAg5b529CRZ3pp",
            HBB: "44rdqLPFi467jDJGsTbov9JKBNCxP4yuvWuD5fRsKGbu",
          },
          collateralVault: {
            SOL: {
              pool: "J8ebxv2aEcTUYHh9Jd7EfE7oZgnt1xiVGN6LeGKURsuw",
              authority: "CFCHz5e3dkTzcWMQjWkwQJEXPyQmM4GGzjj9SunAoYap",
            },
            ETH: {
              pool: "76JSiWhGd84BxrjBJjdadRRCU2nzdCmuPDRFQk1E3rEZ",
              authority: "B3ZxVGRXBpAvjr4KxnwSsCAzTein8ymdKrPkBssFYW9G",
            },
            BTC: {
              pool: "HFsKaZtpehaBHMZDmRSUzsLD1y3j2h2zkTUB2Fzm6v6r",
              authority: "GXtuRXC3jfavm6wjqcWAcnTHzJ5RzK2CFZjQfpuG11Lc",
            },
            SRM: {
              pool: "CZTGDLmYYcaLAqeM3jmSa9EKqfGFkHfutfnKwoK3RDuU",
              authority: "CFCHz5e3dkTzcWMQjWkwQJEXPyQmM4GGzjj9SunAoYap",
            },
            RAY: {
              pool: "BrraFxuaiX6edVcjehczEH8WzBbDPXG9Vq4zFtR31oHs",
              authority: "68HRjkSQitz9LkCTDnYBV7dLFwpKsaSJ3a5Quide3qph",
            },
            FTT: {
              pool: "8mh7DaHYZCKofNiDV27YebsC3uZipbvvTcNmhBYZHF8y",
              authority: "5MdMd77qdokNTek87biwGnnLKQJusBeb7gtih6YWZnqt",
            },
          },
          userPositions: "4M7dZmPhpYQEzT9s3N5PhjDb3VcFrqfCQZBhRQH3FAKF",
          borrowingMarketState: "6rkGfMoG6hvWmzJzdbocgwyGfDwXDyvHsqU7UpyzS2pq",
          stabilityPoolState: "5y7rqAh9ffVSJu6wH73QPXskcqLZmogirw8CW7Fer8cx",
          epochToScaleToSum: "tTzux8myzrDmWoeAyk5KRUrjWYGqEJgHfJqohxDwj8y",
          stablecoinStabilityPoolVault: "835fwEqk2VaHBDAmG3z18HWorqwMURsPsmPEeewk35FZ",
          stabilityVaults: "ANSNagYiiic2uR2CUNRf7PFupUZXW1tefkPBTp16yddh",
          stablecoinStabilityPoolVaultAuthority: "7bChuDYNHqpGpWMvLQ7YTrvGiP3AkQjSwXeZq75MrtXX",
          liquidationRewardsVaultSol: "9ELnAzgZ1tmYHSXGxuG1Cyi5MwwjbmgHrumcWeY4qAiw",
          liquidationRewardsVaultSrm: "x1t7r6PUdEFXQ1a1UXXTVeNxSbYTbPRKUvmKXUiTcHW",
          liquidationRewardsVaultEth: "A3d1soF54pLdZD7EzWtEikrp4okKnqw6eDzatp6C3F3S",
          liquidationRewardsVaultBtc: "6RJemzXE6dzmPofMTnbDjwwBLVtFYtoQc8y7JeTRuxM",
          liquidationRewardsVaultRay: "9WPCCP1BFrnswb5ARYHp3YdUXzpjhoRk5uQLHqXBgdLP",
          "liquidationsQueue": "F3ynJaZ2dHZQAP6zkrr7yGaPrRh2v1wcRNwGhX1ZVZDx",

          liquidationRewardsVaultFtt: "EYSuqHG8NqMV8pGu3XP1Nj4xsKmwUL939Yk53YEuyAYi",
          liquidationRewardsVaultSrmAuthority: "GdDA6Toey1PfrCFg3w8gH7cHpjeZhzGzQJZwo9UZSLJY",
          liquidationRewardsVaultEthAuthority: "AG3rSyQHEqneXdfzwh4eE2X5htr8gxqB7cF46FMdThwY",
          liquidationRewardsVaultBtcAuthority: "HcLq9Z2Ee9FBmcWSsnKnH9tgSC7UbwDh1pEfXyxREmwd",
          liquidationRewardsVaultRayAuthority: "8EvzibXsXZ9cSGNfTTWpwKr3jGTktEad7nrnVyPmipUU",
          liquidationRewardsVaultFttAuthority: "CWHmp1DFrgKwK97cZWMXUR4Z3Fkgjx17MyfEZbjzV2KB",
          borrowingVaults: "2wNHsWtnSt5UdLJbwrA5XNa9FUWtScPc84MHFZpaDwva",
          stakingPoolState: "FEXNKKnT1G19eR69ffMzHvrx7PeLjRYdUN9vwk2DDzkE",
          borrowingFeesAccount: "BKG1NpWMT1dHSswS5U95aMN4dCtmEvQ3MgJ99tSDDFio",

          // pyth - todo move to nested field
          pythSolProductInfo: "ALP8SdU9oARYVLgLR7LrqMNCYBnhtnQz1cj6bwgwQmgj",
          pythSolPriceInfo: "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG",
          pythEthProductInfo: "EMkxjGC1CQ7JLiutDbfYb7UKb3zm9SJcUmr1YicBsdpZ",
          pythEthPriceInfo: "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB",
          pythBtcProductInfo: "4aDoSXJ5o3AuvL7QFeR6h44jALQfTmUUCTVGDD6aoJTM",
          pythBtcPriceInfo: "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU",
          pythSrmProductInfo: "6T1eJbKWyhZXEjmuBej9gPk3SRTagzrEQovCSwAWD57P",
          pythSrmPriceInfo: "3NBReDRTLKMQEKiLD5tGcx4kXbTf88b7f2xLS9UuGjym",
          pythRayProductInfo: "EjtaES3pbMCaNrVFtZ5sT36WPXAnARZxCFsoEr2hsUKJ",
          pythRayPriceInfo: "AnLf8tVYCM816gmBjiy8n53eXKKEDydT5piYjjQDPgTB",
          pythFttProductInfo: "E7ymZgACaSd1fYLf2V7WkAmFkpRiWfAjm49R7bceny9K",
          pythFttPriceInfo: "8JPJJkmDScpcNmBRKGZuPuG2GYAveQgP3t5gFuMymwvF",
        },
      },
    },
    testnet: {
      borrowing: {
        programId: "6JbR96VWfG5P2eFCBPRDFenw6poqGP7RoA4vqx5tNBJf",
        accounts: {
          stablecoinMint: "6w7WUkBpfZwejqesCMgXUTdbtZdGThu1882BNiLzTwc8",
          stablecoinMintAuthority: "2okhqAYAsxcDLWxaKdAJ38G2By9HwDdhTmTmY84UftHP",
          mint: {
            ETH: "htC6eTvy3pUSi2wCurvczo5ZyX9vBBzvPMU4PFxr3TP",
            BTC: "HAKEyaEmSUjMFU4qwXd6mf2Sj5Zas5667w6rcuPBuPst",
            SRM: "GosaYdcVQSAvBjYhfgbHfT1k9LcHZBK9uGUV67J8BDT8",
            RAY: "FG2vjWXXBDYgqj5rZ5VnmTL784KmQaDBRivKJGz3cpTs",
            FTT: "AHgeW347LLVBSU7upSUCnffgSH1ZpuQAg5b529CRZ3pp",
            HBB: "44rdqLPFi467jDJGsTbov9JKBNCxP4yuvWuD5fRsKGbu",
          },
          collateralVault: {
            SOL: {
              pool: "J8ebxv2aEcTUYHh9Jd7EfE7oZgnt1xiVGN6LeGKURsuw",
              authority: "CFCHz5e3dkTzcWMQjWkwQJEXPyQmM4GGzjj9SunAoYap",
            },
            ETH: {
              pool: "76JSiWhGd84BxrjBJjdadRRCU2nzdCmuPDRFQk1E3rEZ",
              authority: "B3ZxVGRXBpAvjr4KxnwSsCAzTein8ymdKrPkBssFYW9G",
            },
            BTC: {
              pool: "HFsKaZtpehaBHMZDmRSUzsLD1y3j2h2zkTUB2Fzm6v6r",
              authority: "GXtuRXC3jfavm6wjqcWAcnTHzJ5RzK2CFZjQfpuG11Lc",
            },
            SRM: {
              pool: "CZTGDLmYYcaLAqeM3jmSa9EKqfGFkHfutfnKwoK3RDuU",
              authority: "CFCHz5e3dkTzcWMQjWkwQJEXPyQmM4GGzjj9SunAoYap",
            },
            RAY: {
              pool: "BrraFxuaiX6edVcjehczEH8WzBbDPXG9Vq4zFtR31oHs",
              authority: "68HRjkSQitz9LkCTDnYBV7dLFwpKsaSJ3a5Quide3qph",
            },
            FTT: {
              pool: "8mh7DaHYZCKofNiDV27YebsC3uZipbvvTcNmhBYZHF8y",
              authority: "5MdMd77qdokNTek87biwGnnLKQJusBeb7gtih6YWZnqt",
            },
          },
          userPositions: "4M7dZmPhpYQEzT9s3N5PhjDb3VcFrqfCQZBhRQH3FAKF",
          borrowingMarketState: "6rkGfMoG6hvWmzJzdbocgwyGfDwXDyvHsqU7UpyzS2pq",
          stabilityPoolState: "5y7rqAh9ffVSJu6wH73QPXskcqLZmogirw8CW7Fer8cx",
          epochToScaleToSum: "tTzux8myzrDmWoeAyk5KRUrjWYGqEJgHfJqohxDwj8y",
          stablecoinStabilityPoolVault: "835fwEqk2VaHBDAmG3z18HWorqwMURsPsmPEeewk35FZ",
          stabilityVaults: "ANSNagYiiic2uR2CUNRf7PFupUZXW1tefkPBTp16yddh",
          stablecoinStabilityPoolVaultAuthority: "7bChuDYNHqpGpWMvLQ7YTrvGiP3AkQjSwXeZq75MrtXX",
          liquidationRewardsVaultSol: "9ELnAzgZ1tmYHSXGxuG1Cyi5MwwjbmgHrumcWeY4qAiw",
          liquidationRewardsVaultSrm: "x1t7r6PUdEFXQ1a1UXXTVeNxSbYTbPRKUvmKXUiTcHW",
          liquidationRewardsVaultEth: "A3d1soF54pLdZD7EzWtEikrp4okKnqw6eDzatp6C3F3S",
          liquidationRewardsVaultBtc: "6RJemzXE6dzmPofMTnbDjwwBLVtFYtoQc8y7JeTRuxM",
          liquidationRewardsVaultRay: "9WPCCP1BFrnswb5ARYHp3YdUXzpjhoRk5uQLHqXBgdLP",
          "liquidationsQueue": "F3ynJaZ2dHZQAP6zkrr7yGaPrRh2v1wcRNwGhX1ZVZDx",

          liquidationRewardsVaultFtt: "EYSuqHG8NqMV8pGu3XP1Nj4xsKmwUL939Yk53YEuyAYi",
          liquidationRewardsVaultSrmAuthority: "GdDA6Toey1PfrCFg3w8gH7cHpjeZhzGzQJZwo9UZSLJY",
          liquidationRewardsVaultEthAuthority: "AG3rSyQHEqneXdfzwh4eE2X5htr8gxqB7cF46FMdThwY",
          liquidationRewardsVaultBtcAuthority: "HcLq9Z2Ee9FBmcWSsnKnH9tgSC7UbwDh1pEfXyxREmwd",
          liquidationRewardsVaultRayAuthority: "8EvzibXsXZ9cSGNfTTWpwKr3jGTktEad7nrnVyPmipUU",
          liquidationRewardsVaultFttAuthority: "CWHmp1DFrgKwK97cZWMXUR4Z3Fkgjx17MyfEZbjzV2KB",
          borrowingVaults: "2wNHsWtnSt5UdLJbwrA5XNa9FUWtScPc84MHFZpaDwva",
          stakingPoolState: "FEXNKKnT1G19eR69ffMzHvrx7PeLjRYdUN9vwk2DDzkE",
          borrowingFeesAccount: "BKG1NpWMT1dHSswS5U95aMN4dCtmEvQ3MgJ99tSDDFio",

          // pyth - todo move to nested field
          pythSolProductInfo: "",
          pythSolPriceInfo: "",
          pythEthProductInfo: "",
          pythEthPriceInfo: "",
          pythBtcProductInfo: "",
          pythBtcPriceInfo: "",
          pythSrmProductInfo: "",
          pythSrmPriceInfo: "",
          pythRayProductInfo: "",
          pythRayPriceInfo: "",
          pythFttProductInfo: "",
          pythFttPriceInfo: "",
        },
      },
    },
    devnet: {
      borrowing: {
        programId: "GaTJcV7MPDxPCJf8DTxdWiA4vE8TctmwBYUSbFjhq8Hu",
        accounts: {
          stablecoinMint: "7vLAoAeiUmnGv1rQKhVX3Zqe5mBZFVyC7rJBVy4rETE4",
          stablecoinMintAuthority: "BaqkPtTjPkrifcXM2FP9n4aYRYPA5J4TqPJziNFypVHL",
          hbbMintAuthority: "79pAUYCa4kEVaq4oR7xBhAC7JCMh3Z22rysxweNfZKj8",
          mint: {
            ETH: "GZTujyA8ZSPWiZv3s2TXW4q2RZN6dHpoqSZm8FCkdRS",
            BTC: "7f1p45Bh5m4g84Vtghj3AUrdHVnJ6EJRzb2t1kzWakA9",
            SRM: "2KfnJBSMaKMDQAcdCCZLbeJweiHbsff1rTr5ehw9eFzu",
            RAY: "GR7XB2qjCDtwC3wqA1FjgksamfV5sPrPQvAmsoZZwg7q",
            FTT: "FvWwk8gK8jRE9FeHzS1CHUjVHjQVgAfrYeQJ9iKHQjyp",
            HBB: "BL5bFLzRcVVaUzon3PvkuyyPWQjzZ4DeLUt6PJfuCqY1",
          },
          collateralVault: {
            SOL: {
              pool: "3mpzv1aXAE5hnnu8EKQnqoAau4xwtsxdrti5EhPGL2Nx",
              authority: "3Gwh6sgvMrJNdAcYLRqDiir2tuoWMnJ2ga4nmQGmco9g",
            },
            ETH: {
              pool: "8LkgKsELty21sMdDmZrq4gZG6AQWHW4M44eywL4ankUc",
              authority: "GvEK3EAQt5ee7m273ptrvGQMW4FqoGWoNgsxtokcQcZF",
            },
            BTC: {
              pool: "7hv3PHsschZ329Nra9KWe7DhgDQAezExYpbfGa8ryHYK",
              authority: "CSpNHJDCkS85pkQxnPbfUicmWn284AE4RgKecy1WDdtc",
            },
            SRM: {
              pool: "6CqYCab8qJQsN8fyxuWDqMtHnfjNzVogGkZAAMZQgssL",
              authority: "3Gwh6sgvMrJNdAcYLRqDiir2tuoWMnJ2ga4nmQGmco9g",
            },
            RAY: {
              pool: "6fiM6Fb5xuVpeh6G1VTZWAGSQwBwhLL8LqTSd6XBo7Ps",
              authority: "AjzmDLhoy7pGaAFnL8b2phHwyfD9vzDmEtHZcUAi7vmB",
            },
            FTT: {
              pool: "HTCUgetU5svy1nD61uLFRByDNtj8D78msjwef6qNudXJ",
              authority: "7STvoVpjjgnpPAqUMCxzNePUum7qU7S7jzg2xCKGofpm",
            },
          },
          userPositions: "6cJP3QXpoieSqPryfH8sifkQ3wJM2SBiPVR7jAf5VMkY",
          borrowingMarketState: "6mH9EwNjsDm1J9kTbndQtgSKKpXPg59sWfgi7jkxMkW9",
          stabilityPoolState: "HRbj4gTt4EPK9H7jwBWudZvRdUfn8etXPXQaBt7Am7Zk",
          epochToScaleToSum: "GeNr4km9tYfQc49SHpuEcw3aKeNy2i6tdBoEAoxPQfxb",
          stablecoinStabilityPoolVault: "8CnMxE8bKgHBWSKjZEZ4175SFbHoJ34GcNrszaviM6YP",
          stabilityVaults: "2y2u9x5qMqRerZkewAsRNji9ocHz7V7RMgiSddJSDjKC",
          stablecoinStabilityPoolVaultAuthority: "7KvLCBMMe8AtH8A7w2AcJanYHLgGnp9Ln768WZPELUx8",
          liquidationRewardsVaultSol: "HsXyhNMc2DnqA1PKLDkqfQa4ujdNYXhQ7yHQB4WurxmD",
          liquidationRewardsVaultSrm: "7hkMdLhgjUCHwWtHLqHtcLwBESWVGoqVwXDcr2U7JVQD",
          liquidationRewardsVaultEth: "GLr977b8E4E9yQfJVxvEm6yNqWpt17FHqjeLLr4zbkQn",
          liquidationRewardsVaultBtc: "8xQVroJcJdjHNGzfuXL5j5wNaFYr1LQHk4K14UN5uats",
          liquidationRewardsVaultRay: "EgcjTp5WxLCSrtqnVRdtmSBNZroUrZe3DQCiTrzfh6tN",
          liquidationRewardsVaultFtt: "A5mNNbZznfQjMay5yXtc7tEWmMmWxGjTrzXrbqWRpfPa",
          liquidationRewardsVaultSrmAuthority: "Hr9cWAGEf1YV7K7qf7icqZP7p9meVrcvTBnbHwMPfRff",
          liquidationRewardsVaultEthAuthority: "66xi1hLcsNgMubF4QGC2nioJo3d9ivVPtRdkr8K4XUvB",
          liquidationRewardsVaultBtcAuthority: "HL9SJSTgGcTkV3RVU7ZwYzyTUpwDmwKAakgaap39PGgm",
          liquidationRewardsVaultRayAuthority: "BL1yfezHn6ZKuoyAxeFePiRp4UASV57kBqeW1a7c5pGR",
          liquidationRewardsVaultFttAuthority: "BQagS41wsuC7yF5V5rdfTGepeRwDcWXXkMVaKrJnq2s8",
          borrowingVaults: "61ZjD6FtZC5T3Rh7bta96DuRKJJtcnYvmVbHpSujRpKz",
          stakingPoolState: "1TqzYNyZrdua3pWbLBEhTR3NWNirFzp6yZivAi8CseV",
          borrowingFeesAccount: "7UMr3afkHuD3BbahoMx3cGWUdCKGnom4Vh6dMcxztDap",
          "liquidationsQueue": "F3ynJaZ2dHZQAP6zkrr7yGaPrRh2v1wcRNwGhX1ZVZDx",

          borrowingFeesVaultAuthority: "G9MR1U3U2KqoUCwEaaCsJVYjsNAoiJu3aQsz6oiat7s5",
          stakingVault: "FxnY7k8JrNEhUsVYGe8EX2gsWZnKqSqRfEvF1NC4eHQD",
          burningVault: "75unVptPNPp8kcwvLxfE5pfNSBhcQfu4sh3iZqXQFyTt",
          burningVaultAuthority: "HN2nJMaNKLNnbNcFRCo2NLsAu9PQhSRmSiefxWcZ8NAA",

          // pyth - todo move to nested field
          pythSolProductInfo: "3Mnn2fX6rQyUsyELYms1sBJyChWofzSNRoqYzvgMVz5E",
          pythSolPriceInfo: "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix",
          pythEthProductInfo: "2ciUuGZiee5macAMeQ7bHGTJtwcYTgnt6jdmQnnKZrfu",
          pythEthPriceInfo: "EdVCmQ9FSPcVe5YySXDPCRmc8aDQLKJ9xvYBMZPie1Vw",
          pythBtcProductInfo: "3m1y5h2uv7EQL3KaJZehvAJa4yDNvgc5yAdL9KPMKwvk",
          pythBtcPriceInfo: "HovQMDrbAgAYPCmHVSrezcSmkMtXSSUsLDFANExrZh2J",
          pythSrmProductInfo: "6MEwdxe4g1NeAF9u6KDG14anJpFsVEa2cvr5H6iriFZ8",
          pythSrmPriceInfo: "992moaMQKs32GKZ9dxi8keyM2bUmbrwBZpK4p2K6X5Vs",
          pythRayProductInfo: "3BtxtRxitVDcsd7pPUWUnFm9KvmNDy9usS4gE6pUFhpH",
          pythRayPriceInfo: "EhgAdTrgxi4ZoVZLQx1n93vULucPpiFi2BQtz9RJr1y6",
          pythFttProductInfo: "63VWd2FVbukVozZ1okHt8wVMq7enAYFXYnmp2DUQtBBJ",
          pythFttPriceInfo: "6vivTRs5ZPeeXbjo7dfburfaYDWoXjBtdtuYgQRuGfu",
        },
      },
    },
    localnet: {
      borrowing: {
        programId: "8v1DhJaewvhbhDmptNrkYig7YFcExsRKteR3cYjLw2iy",
        accounts: {
          "stablecoinMint": "ESus71pYgq74bY5aCHx8AMXKrm7JkCFcoxER3Q6Lesx3",
          "stablecoinMintAuthority": "GppAS8mEaFtwB1kc9TXcX9uDzBKojFGzGwe7XyZgVyg4",
          "hbbMintAuthority": "5zkvdw5SpWdffNe5iM5N4xx5T4YdivNieGSfT1V5LgPy",
          "mint": {
            "ETH": "DLrJwTEhMgBqexobbaTLbnjHC3dkznHeircooEvg7C8C",
            "BTC": "EnRbXnJs4PmBcGk211zPCVZGhGpXAVwGoAc4UCiMcEH7",
            "SRM": "4MNAzMpbMP6TxP7dizkxh6CTqS4GYxK8emQ6qzKFM6ps",
            "RAY": "DPkZQA2sy3gn91QSvy2s8ufVWsmiDGXnZqoL6QpEzHsX",
            "FTT": "5qZ9UJFim5siTn6xEHXXoxCaUZEjPXXPBXsuZCoFaHqz",
            "HBB": "5MdrzCy4QFPDmSrrtk4FSEC1Rr5V1hmPVNefJUgmZK6m"
          },
          "collateralVaultsAuthority": "691MsPc7K6w4byBipznpCmb9NaPg4jCGCQMKg7KYmdj9",
          "collateralVault": {
            "SOL": "CdeV28SnqhYtT5ADuGBq5sKHDcr96nKR9WvGY74iwUxk",
            "ETH": "4QqzXo5nRFUL7Gp6k4brsNbCjbpM8UmhHeqopBMiN25o",
            "BTC": "DjZp2SubC82EBykxwkRG4i6b3PU1m12RcPaZCcRzX3AQ",
            "SRM": "53RcpzBKBVBhHq8aAAVT2AFEZo3qVimBCNLyjCZZUhB7",
            "RAY": "9ZtB2A5jirb9o6aeBJxBbrCY8nkoRUZHQB8R7Cvpzs5g",
            "FTT": "Hkw3mbFa5nvnaek76PR8oxD9SP4QihkrDqQBnprx4cad"
          },
          "redemptionsQueue": "FjXvFakEEkBcVgBJW38jC2ndpDNkt3GfidWiq9jGf9sm",
          "liquidationsQueue": "3AxhinoKEWCfvDLEt4rny8SL1PwLWCzcSa8GwPLei23v",
          "borrowingMarketState": "38Uw78bM5oypDtpWjPACqbDVaxUR1f9ZZeT5WF4vkFmV",
          "stabilityPoolState": "B8DgqBRSwqkx85cJ4UFcptoNLqKDPzLT27pXAQexep1",
          "epochToScaleToSum": "H2kVmvENF6AEyfZwATSnqaRger2v5NstErUhgVcX8Rvm",
          "stablecoinStabilityPoolVault": "GdxqKexcQfuxB9pVTiEHm24b3nSPQwj9hNBS7QvKsjz1",
          "stabilityVaults": "9shE6R9Bex2rPvpmQCeDBLvdXnvUfrkLxQqZXvCHVfyu",
          "stablecoinStabilityPoolVaultAuthority": "ffkYiBPKNV2vXDJ7jEiAcNoDAiDSrZ3a3jCte6ceuvZ",
          "liquidationRewardsVaultSol": "5NiRqxYE6jWP6ULCRes87BN2k9GM71WgjZScjtmXYmPd",
          "liquidationRewardsVaultSrm": "5xPJ3ytqdujtnFFR7hNfLXtt16XQaJU1FHuN71kMFbEt",
          "liquidationRewardsVaultEth": "Ad7tGghzfG5s5TUQ57SQbTdsYHPDnteweCvaTegEEfMf",
          "liquidationRewardsVaultBtc": "A1HWaJLLhcpRuQFPkhetS5cxEEwFtxbN5k5UV2Ykaa1T",
          "liquidationRewardsVaultRay": "C8YqummBenT5QM3dmt7JdyY1cn9Wo7H22dHyTW16PhYc",
          "liquidationRewardsVaultFtt": "ALgdTeZNvY5xEkjybEjW1P9PM9pDDDafGbuSwMMZicar",
          "liquidationRewardsVaultAuthority": "DKxXeeT3W1oWSNm1m49HiKWU81z5FQFYkPJkyV9YEWxn",
          "borrowingVaults": "8XTkNQjHXhw3kdnGWn3CFR7kZ9Wozr3Qx41zjuYEvR97",
          "stakingPoolState": "FYVthxHaMqJ5x16XtmyQWa1Lc9tdeU1dewssuBUgrb11",
          "borrowingFeesAccount": "Bo6rtzWa7m3g3YWqKmXEAh4AGLnjXfZCGisxp7BoNDXm",
          "borrowingFeesVaultAuthority": "8rywVdwJp8QnFPiSQDWghDAmahZ9yHADdS9Gk8rhuARB",
          "stakingVault": "GDh4oax5Mqm2Q5fQm6mGYqfCriMzBm1k6zHoqqoGMid2",
          "burningVault": "9S6TMm9qJYMFZ94iJH8uj5sENtiKV3ZjD6M5wbykXGWU",
          "burningVaultAuthority": "4t69ek9prg6snT34vyPTynvU3Hpffw2P2xvEEC1M31Pk",
          // pyth - todo move to nested field
          pythSolProductInfo: "ALP8SdU9oARYVLgLR7LrqMNCYBnhtnQz1cj6bwgwQmgj",
          pythSolPriceInfo: "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG",
          pythEthProductInfo: "EMkxjGC1CQ7JLiutDbfYb7UKb3zm9SJcUmr1YicBsdpZ",
          pythEthPriceInfo: "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB",
          pythBtcProductInfo: "4aDoSXJ5o3AuvL7QFeR6h44jALQfTmUUCTVGDD6aoJTM",
          pythBtcPriceInfo: "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU",
          pythSrmProductInfo: "6T1eJbKWyhZXEjmuBej9gPk3SRTagzrEQovCSwAWD57P",
          pythSrmPriceInfo: "3NBReDRTLKMQEKiLD5tGcx4kXbTf88b7f2xLS9UuGjym",
          pythRayProductInfo: "EjtaES3pbMCaNrVFtZ5sT36WPXAnARZxCFsoEr2hsUKJ",
          pythRayPriceInfo: "AnLf8tVYCM816gmBjiy8n53eXKKEDydT5piYjjQDPgTB",
          pythFttProductInfo: "E7ymZgACaSd1fYLf2V7WkAmFkpRiWfAjm49R7bceny9K",
          pythFttPriceInfo: "8JPJJkmDScpcNmBRKGZuPuG2GYAveQgP3t5gFuMymwvF",
        },
      },
    },
  },
};



